### ISSUE TITLE
Rendering Issue when not in dialog 

### ISSUE THREAD

**Issue by zmoshansky** [bendavis78/paper-time-picker#8] opened 2015-08-24 18:32 UTC
Used on polymer 1.0+; It renders fine when in a dialog.
Works great:

```
    <paper-dialog id="dialog" modal class="paper-time-picker-dialog">
      <paper-time-picker id="timePicker"></paper-time-picker>
      <div class="buttons">
        <paper-button dialog-dismiss>Cancel</paper-button>
        <paper-button dialog-confirm>OK</paper-button>
      </div>
    </paper-dialog>
```

Renders all the clock numbers on top of each other:

```
        <paper-time-picker id="timePicker"></paper-time-picker>
```

![screenshot from 2015-08-24 11-30-03](https://cloud.githubusercontent.com/assets/3180807/9448815/8ad79c0e-4a53-11e5-8b0a-c3fdd43177c5.png)

**Comment by bendavis78** [comment] 2015-09-21 08:00
Can you give some code to reproduce this?

**Comment by bendavis78** [comment] 2015-09-21 08:01
I'm unable to reproduce this, but I've been making a bunch of bugfixes lately. Can you check again using master?

**Comment by ghost** [comment] 2015-10-27 21:14
I think `paper-input` interacts with `paper-time-picker`, because:

This works to me:

```
<paper-button on-tap='showDialog'>dsfs </paper-button>                        
<paper-dialog on-iron-overlay-closed="closing" id="dialog" modal class="paper-time-picker-dialog">
  <paper-time-picker id="timePicker" force-narrow></paper-time-picker>        
  <div class="buttons">                                                       
    <paper-button dialog-dismiss>Cancel</paper-button>                        
    <paper-button dialog-confirm>OK</paper-button>                            
  </div>                                                                      
</paper-dialog>
```

and this not

```
<paper-input on-tap='showDialog' label="Input label"></paper-input>           
<paper-dialog on-iron-overlay-closed="closing" id="dialog" modal class="paper-time-picker-dialog">
  <paper-time-picker id="timePicker" force-narrow></paper-time-picker>        
  <div class="buttons">                                                       
    <paper-button dialog-dismiss>Cancel</paper-button>                        
    <paper-button dialog-confirm>OK</paper-button>                            
  </div>                                                                      
</paper-dialog> 
```

The only difference is triggering node.

**Comment by radiia** [comment] 2015-11-04 16:08
Same problem for me, even with paper-button and using it inside a paper-dialog element:

<img width="667" alt="screen shot 2015-11-04 at 17 06 36" src="https://cloud.githubusercontent.com/assets/3583180/10943821/7b68e5d8-8316-11e5-8642-95313149997b.png">

**Comment by ghost** [comment] 2015-11-04 16:15
This https://github.com/bendavis78/paper-time-picker/commit/d8ec0fb08245b43b94978f1ce6cc5bacfc09f6c4 from https://github.com/bendavis78/paper-time-picker/issues/16 solved my issue.

**Comment by radiia** [comment] 2015-11-04 16:29
Thank you @xliiv , it works perfectly.
Saved my day!

**Comment by masonlouchart** [comment] 2015-11-15 21:41
What do you think about make soon a new release and close this issue ?

**Comment by bendavis78** [comment] 2015-11-24 10:34
This should be fixed in master.

**Closed as completed by bendavis78** 2015-11-24 10:34 UTC
