### ISSUE TITLE
Not working on Chrome 52

### ISSUE THREAD

**Issue by Kyle-Falconer** [bendavis78/paper-time-picker#44] opened 2016-08-31 18:22 UTC
I get this in the console:

```
Behavior Polymer.IronResizableBehavior not found when mixing properties into paper-time-picker!
Behavior Polymer.IronResizableBehavior not found when mixing properties into paper-clock-selector!
```

<img width="573" alt="screen shot 2016-08-31 at 11 20 38 am" src="https://cloud.githubusercontent.com/assets/1034255/18141099/0b0887aa-6f6d-11e6-9e1f-e7b8eb4849fc.png">

**Comment by dasurid** [comment] 2016-09-02 04:17
I see the same thing using safari on the component demo page.

**Comment by bendavis78** [comment] 2016-09-12 01:18
I'm unable to reproduce this issue. Can you try the latest version?

**Comment by ronnyroeller** [comment] 2016-09-12 10:32
It works for me with the latest checked-out version but the demo linked from the Github project page doesn't work (http://bendavis78.github.io/paper-time-picker/).

I'm using "Chrome 51.0.2704.106 (64-bit)" on Fedora.

**Comment by giubil** [comment] 2016-09-12 10:35
I have the same using Chrome 53.0.2785.101 on mac

**Comment by dasurid** [comment] 2016-09-13 02:08
The component page demo still doesn't work on a mac, just a blank area where the clock should render.  I have tried  Safari, Firefox and Chrome and all exhibit the blank clock.

**Comment by jonsmithers** [comment] 2016-10-24 00:56
For what it's worth, I found that a `neon-animated-pages` element is collapsed to 0 height. If I give that element `height:100%;` and trigger a resize, the clock shows up.

![screenshot from 2016-10-23 20-53-53](https://cloud.githubusercontent.com/assets/2660313/19630960/e2120d74-9962-11e6-88e0-cf2b1df11695.png)

I'm using Chrome 54.0.2840.59 (64-bit) on ubuntu.

**Comment by jonsmithers** [comment] 2016-10-24 01:08
Also, `Polymer.IronResizableBehavior` is undefined in the console. ...could it be a missing import?

![screenshot from 2016-10-23 21-05-53](https://cloud.githubusercontent.com/assets/2660313/19631063/ca7e6ee4-9964-11e6-999d-99967567a725.png)

I'm seeing this in Firefox too.

**Comment by tiesselune** [comment] 2016-10-28 00:04
I've witnessed this on Chrome (Win), only in the demo pages. Using it in my project works fine.

**Comment by admwx7** [comment] 2017-09-14 22:18
This has a merged in fix, closing.  If it persists open a new issue and tag me please!

**Closed as completed by admwx7** 2017-09-14 22:18 UTC
Labels: can't reproduce
