### ISSUE TITLE
Can't change hours

### ISSUE THREAD

**Issue by mrbinr** [bendavis78/paper-time-picker#36] opened 2016-05-15 07:31 UTC
Hi 
I'm trying to use paper-time-picker but i can't change hours ... nothing append, and when i click on minutes, number color change into white and i can't see then anymore :(

Best Regards
Pascall

**Comment by olegabr** [comment] 2016-06-29 17:27
+1
ubuntu, firefox, chrome

**Comment by bendavis78** [comment] 2016-08-07 21:46
Can't reproduce this on my end. Please see README under "Reporting Bugs".

**Comment by admwx7** [comment] 2017-09-14 22:21
@mrbinr and @olegabr if either of you are still having this issue, please let me know, otherwise I'm going to close this out since I'm not having this issue either.

**Closed as completed** 2017-09-19 18:48 UTC
Labels: can't reproduce
